parameters:
  htmltopdf_path: '/usr/bin/chromium'   # MacOs: /Applications/Chromium.app/Contents/MacOS/Chromium
  htmltopdf_service_url: ''             # Should be a complete url like https://example.org/yeswiki/?PagePrincipale/pdf
  # Advanced
  # Has to comply with HeadlessChromium::createBrowser() options
  # see https://github.com/chrome-php/headless-chromium-php#options
  htmltopdf_options:
    windowSize: [1440, 780]
    noSandbox: true
    headless: true
    userAgent: 'YesWiki/4.0'
    startupTimeout: 60
    sendSyncDefaultTimeout: 10000
    customFlags:
    - '--crash-dumps-dir=/tmp'
    # debugLogger: 'php://stdout'
  page_load_timeout: 120000 # duration before considering the pageload completed (120000ms = 2 minutes)
  # if you want to propose this website as a service for other domains
  htmltopdf_service_authorized_domains:
  #  - 'example.org'
  #  - 'another-one.com'

  # ADVANCED SETUP
  # Configure this when the HTTP server does not have access to the YesWiki via its public URL.
  #
  # Eg, if Docker/base_url is https://example.com/? and Apache runs as http://localhost:8000,
  # … then `htmltopdf_base_url` value should be `http://localhost:8000/?`.
  # Use cases: reverse-proxy, within a YesWiki Docker container.
  htmltopdf_base_url: ~
  #htmltopdf_base_url: http://localhost:8000/?
